{% set version = "0.13.3" %}
{% set name = "pandas-gbq" %}
{% set sha256 = "d96b7fd29021892ba55a6d094e8f9ceb1973a5e72b819d0a01b26f12e132a205" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps -vv

requirements:
  build:
    - pip

  run:
    - python >=3.5.0
    - setuptools
    - pandas >=0.19.0
    - pydata-google-auth
    - google-auth >=1.0.1
    - google-auth-oauthlib >=0.0.1
    - google-cloud-bigquery >=1.11.0,<2.0.0dev

test:
  requires:
    - python
    - pip
  imports:
    - pandas_gbq
  commands:
    - python -m pip check

about:
  home: https://github.com/pydata/pandas-gbq
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Pandas interface to Google BigQuery

  doc_url: http://pandas-gbq.readthedocs.io
  dev_url: https://github.com/pydata/pandas-gbq

extra:
  recipe-maintainers:
    - jreback
    - leahecole
    - parthea
    - tswast
