{% set version = "0.3.0" %}
{% set name = "pandas-gbq" %}
{% set sha256 = "b82a61aee408b349ba2a5725fc29d3d2fa33ed0be0a77d31ac1e07676401d0a0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pandas
    - google-auth >=1.0.1
    - google-auth-oauthlib >=0.0.1
    - google-cloud-bigquery >=0.28.0

test:
  imports:
    - pandas_gbq

about:
  home: https://github.com/pydata/pandas-gbq
  license: BSD 3-clause
  summary: 'Pandas interface to Google Big Query'

  doc_url: http://pandas-gbq.readthedocs.io
  dev_url: https://github.com/pydata/pandas-gbq

extra:
  recipe-maintainers:
    - jreback
    - parthea
    - tswast
