{% set name = "pandas-gbq" %}
{% set version = "0.16.0" %}
{% set sha256 = "a1b8e8b34a202b00166ca276180d9195ff589f5a0dfa37e7a191022d8a90376f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps -vv

requirements:
  build:
    - pip

  run:
    - python >=3.7.0
    - setuptools
    - pandas >=0.23.2
    - pydata-google-auth
    - google-auth >=1.0.1
    - google-auth-oauthlib >=0.0.1
    - google-cloud-bigquery >=1.11.0,<3.0.0dev
  run_constrained:
    - tqdm >=4.23.0

test:
  requires:
    - python
    - pip
  imports:
    - pandas_gbq
  commands:
    - python -m pip check

about:
  home: https://github.com/pydata/pandas-gbq
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Pandas interface to Google BigQuery

  doc_url: http://pandas-gbq.readthedocs.io
  dev_url: https://github.com/pydata/pandas-gbq

extra:
  recipe-maintainers:
    - jreback
    - leahecole
    - parthea
    - tswast
