{% set version = "0.12.0" %}
{% set name = "pandas-gbq" %}
{% set sha256 = "c24beb52352f01d095e7f2627b94a6fd603a81d663ead91d9100903817aadc4b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: True  # [py2k]

requirements:
  build:
    - python
    - setuptools
    - pip

  run:
    - python
    - pandas >=0.19.0
    - pydata-google-auth
    - google-auth >=1.0.1
    - google-auth-oauthlib >=0.0.1
    - google-cloud-bigquery >=1.11.0

test:
  imports:
    - pandas_gbq

about:
  home: https://github.com/pydata/pandas-gbq
  license: BSD 3-clause
  license_file: LICENSE.txt
  summary: 'Pandas interface to Google Big Query'

  doc_url: http://pandas-gbq.readthedocs.io
  dev_url: https://github.com/pydata/pandas-gbq

extra:
  recipe-maintainers:
    - jreback
    - parthea
    - tswast
