{% set version = "0.8.0" %}
{% set name = "pandas-gbq" %}
{% set sha256 = "bb8f8d4ad07eddde113e9602edf97f68a5e06d6d299f7d397367341271a12ada" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip

  run:
    - python
    - pandas
    - google-auth >=1.0.1
    - google-auth-oauthlib >=0.0.1
    - google-cloud-bigquery >=0.32.0

test:
  imports:
    - pandas_gbq

about:
  home: https://github.com/pydata/pandas-gbq
  license: BSD 3-clause
  summary: 'Pandas interface to Google Big Query'

  doc_url: http://pandas-gbq.readthedocs.io
  dev_url: https://github.com/pydata/pandas-gbq

extra:
  recipe-maintainers:
    - jreback
    - parthea
    - tswast
