{% set version = "0.13.2" %}
{% set name = "pandas-gbq" %}
{% set sha256 = "bc3a615c92df76490be33ae1efe60e82b8affd196e39f4f6c9c76d67c32e3d46" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps -vv

requirements:
  build:
    - pip

  run:
    - python >=3.5.0
    - setuptools
    - pandas >=0.19.0
    - pydata-google-auth
    - google-auth >=1.0.1
    - google-auth-oauthlib >=0.0.1
    - google-cloud-bigquery >=1.11.0

test:
  requires:
    - python
    - pip
  imports:
    - pandas_gbq
  commands:
    - python -m pip check

about:
  home: https://github.com/pydata/pandas-gbq
  license: BSD 3-clause
  license_file: LICENSE.txt
  summary: Pandas interface to Google BigQuery

  doc_url: http://pandas-gbq.readthedocs.io
  dev_url: https://github.com/pydata/pandas-gbq

extra:
  recipe-maintainers:
    - jreback
    - leahecole
    - parthea
    - tswast
