travis:
  secure:
    BINSTAR_TOKEN: CWDpkWB73SPX+lon/J8s+8t3hpnHEDZNZuUZ7seZNwEPlzxVZ/23pU6r+Kbm8OAThnQfngSYXmLnEfkEaYL70oFAFznIcAp+zYpbvrZvswlZWyfT4UnhnUueSbeJn9CQqXZdHPGI9rhRD9nc/D1wUlCKDQplsS0Uw8UBCK6eV0dU+BLRvorFszP3mEI79B9pYL8w7k5t+ougWBK9Qyf9GpvvYKC0Hyw0NbvLA1hPFDFu65ceZaA9MYcs0KCOSc0ka7l6v1uxb4Fw7zWv1A7zHIq5/16EV4dRwkBB6Wd5eIJnJ1bpbZ7U4mQWKzN2YlHsLaxMN4hQ4JvHZiSEnEHB33nqLHRq0xNzO5TmGbRx0JbZBPx2KPcaRN8CTvlkVCLe7o4QquSu+Po9fdTBP3WCS4VNkX6D2oy5376PoT+seLC7Nug6cpWFskrGx51YeCRM9T9MDq0Go4Ual3Z6tCQKemy/CUqfhLXLJkVjY9l+bpFQvvhA7upifv6BE6C+zg6KjGP57EBHl9NHsgEjF/g8jMFwoQ8qUJ32c1VKeLkm2BZ7bEasS7xtLykskWMfbcJprSSJYYz/+um2AN97AhN1jaqqv+yb7B46nxcCboAw4WUNhISQSvU8V3az9Guq64aijjHisY7EgLoAJ1T13acN9Hp0UIOxWCPIhzhEHkmTugk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
