travis:
  secure:
    BINSTAR_TOKEN: gTL7KDc/Y7nzeh6tc1JpCf39dBxp+PfpH/DIO8xG5/qn2rGnH3Z7115Dd8Ianrr9LZUm4KrcHHs2z33TyXBVuuv3d419yPfCtYbEGQLK/ZmFpe825Y7ygrl6+Y/D17yb0Gf//OT2clGixIqJvgcKMFgPk7K7uEiDbFbPOJoxopQm61YBazEwrGXc4yzZJneqF/iJ6wB2x6gc0pyAuLaM0vl4kUGiLUiqaOtB3riHyml+7M7o40t8eBMzj0q6AGjuHQbnhZaLIbcIMrgW5udvsbCXAHt/dMa3Scal4l4HnHxS8xlWQmfAPpcAg0MrXw5AeEEBFwSMrcaPI3g2plHxhzWGCXu/M+1YCibE38oWUJGrMpNx+oT/5m2KB7sxIhNra/qJkiZ0TEx8oTScCvuhxlgwJGdUw/1Jrnbk1POs0OqLRstpj/lvFcDntQ/uJFsfEaz4BFwYJygeASGbcVkIk3aou4njZK2Y2R49XhgYnok3UasdRQyUt9pNdSxWyKg6TVGyWP0uvE+iNgBhC5dSIPLz2CJLehe5lISDT1wApn20uZPcYaCYCuPKI/ikz1r/Fiym2R6/1GxZyiOi3xCinnzhZXNDe8XjvJddE50GdblW/uzYhkLJO0TruoRO9yL8H1FQUK4oK4600fOCZ/3LfMIL+C40oDUK6D7oFfNPuyc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
