travis:
  secure:
    BINSTAR_TOKEN: NSX3FrYAeVQpbd13RXrDSJ6k965S90jv1S4JG98cljlR/47vTh6vPWFepJi5nA7pLMkyRWBDwIyxNkndVaEKGRujxheHqJowcCPhyZ8/Z32uB84XH8PPmaSOnlrlb1TXogKgxoNxuki8cm0FiFfeXJyU3JGe56rmYqyiwDKQ9EdTFIFpmKBM//nxXaac3LgflkjF8cHfSsBxKEy5AOcVKU/O0nihRubgMW9FBfwgQAy746cDuTUqr4XxUWSBhy1poOQ0bvjUPdRsS4zhdVxvbJYYf3pjbUD6ErJoHpvECh09R1Nc1T84gVCn5U4LQ8o2rkSCwrJKedVtSiPo/zKk43sQodeLbxI9OjR2xeyW9jY3mOptbSCLg9S5mmXGFnfa51neUvt5qUUPWcJKm4dpmK2spI0Pw7r8dWvI7CAKRPlT/CgHdH05scezZNFpLa/1RyStUqTjwuUfGnxNb+/QhVOhlvcuFyujkirZUxwxxL/+GTl/0T3qQveOVlbxA2oY8LlYx27DhI9VLo2AL82doD7ikqRkQC4hwhUAAbf9Cp0Dz96jrpZp1RNqMkCKyd1K0/phl7lJ7C35yV0PmHlSWrXHtXKmBJHjH6h+BiX/OQqxc6Mt2u1XBo2pM2fL5eRxlVoe7x813d4bfpMbjOeDEwjD5MdY7FuhSh3sLuQ2Y8E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
